### ISSUE TITLE
Obwohl NAs entfernt wurden, werden sie im Dataframe immer noch angezeigt

### ISSUE THREAD

**Issue by savannahcattarius** [datascience-mobi/2021-topic-01-team-05#1]
@sholderbach In dem chunk {r S5 Replacing NAs in prism_reduced with the column means} haben wir von prism_reduced versucht die NAs mit den jeweiligen means zu ersetzen und dachten auch, dass das geklappt hat. Bei der Summary von prism_reduced_no_NAs sieht man aber dass noch 7667 NAs im dataframe drin sind. Warum hat das nicht geklappt und wie können wir die NAs richtig durch die jeweiligen means ersetzen?

**Comment by sholderbach** [comment]
Kann es sein, dass in eurem subset moeglicherweise Spalten existieren, die nur NA enthalten? Dann wird mean(...,na.rm = TRUE) ebenfalls NA fuer das element ausgeben.

**Comment by sholderbach** [comment]
Konntest du das Problem beheben?

**Comment by savannahcattarius** [comment]
Ja, danke!!
